### ISSUE TITLE
netstat -b does not run as elevated.

### ISSUE THREAD

**Issue by T-G-U** [nu774/sudo-for-cygwin#5]
tgu bin $ ./sudoserver.py -nw &
[1] 11684
tgu bin $
tgu bin $ sudo netstat -b
Accepted connection from ('127.0.0.1', 63778)
                                             The requested operation requires elevation.
FIN received
Closing connection
tgu bin $

BTW, '-nw' switch does not do its job, output from server is still send to terminal (as shown above - test has been done in the same terminal session).

**Comment by nu774** [comment]
Have you read the doc?
You have to run sudoserver.py with elevated privileges.
