### ISSUE TITLE
Fork with more security

### ISSUE THREAD

**Issue by Chronial** [nu774/sudo-for-cygwin#9]
Since nu774 said this project is [abandoned](https://github.com/nu774/sudo-for-cygwin/issues/8#issuecomment-343668915) and I was unhappy with the complicated setup and lack of security, I created a fork that has (hopefully 🙂 ) proper security and way simpler setup.

* It does not need a running background process, but opens a UAC prompt for every execution in exchange.
* It does not depend on any packages outside the stdlib, simplifying the setup.

You can find it here: https://github.com/Chronial/cygwin-sudo

@nu774 Your repo did not contain a license, so I hope you are fine with me doing this. If this is not the case, please notify me and I will take my repo down. Otherwise I would like to license my version under GPLv2, if that is ok with you?

**Comment by nu774** [comment]
You can take this project as public domain. Your fork is OK.

**Comment by Chronial** [comment]
thx
